### ISSUE TITLE
Not working with Laravel 5.7

### ISSUE THREAD

**Issue by codercotton** [ksungcaya/phpass-laravel#6]
Hello - thanks for your work on this!

I'm trying to integrate this into a brand new Laravel project (currently v5.7.25), but am not able to get the default Auth framework to use Phpass - it's still returning the bcrypt hash from the Hash:: calls.

Steps to reproduce:

1. New Laravel installation
2. artisan auth:make
3. artisan migrate
4. register a new user, using default Laravel bcrypt password encryption
5. composer require ksungcaya/phpass-laravel
6. added service provider to config/app.php providers array
7. log in with user

Expected result:
Laravel auth uses Phpass encryption for password, login fails

Actual result:
Laravel auth uses default bcrypt encryption for password, login succeeds 

Any ideas would be much appreciated!

**Comment by ksungcaya** [comment]
hello, apologies for the late response. When using this library, you need to setup this first before registering any user. The reason why it did not work in your case is because when you registered the user, PHPass was not yet setup so it used the default hashing of laravel which is bcrypt. After you added the package, it will then use PHPass as the default hashing hence the authentication error as it was using a different hash mechanism.

**Comment by codercotton** [comment]
Thanks for your reply.

The point is that it IS working after enabling phpass... it shouldn't work because the PHPass hash shouldn't match the default bcrypt hash.  It seems like the hash:: calls are not being updated and it's running without the PHPass integration.
